
// USER ACTIONS //

// POST

export const POST_POST_USER_LOGIN = "POST_POST_USER_LOGIN"
export const POST_POST_USER_LOGOUT = "POST_POST_USER_LOGOUT"
export const POST_POST_USER_REGISTER = "POST_POST_USER_REGISTER"

//GET 

export const GET_GET_LOGGED_USER = "GET_GET_LOGGED_USER"
export const GET_GET_USER_DETAIL = "GET_GET_USER_DETAIL"

// END USER ACTIONS //

// SONG ACTIONS //

//POST

export const POST_POST_SONG = "POST_POST_SONG"
export const POST_POST_LIKE_SONG = "POST_POST_LIKE_SONG"
export const POST_POST_COMMENT_SONG = "POST_POST_COMMENT_SONG"

//GET

export const GET_GET_LIKED_USER_SONGS = "GET_GET_LIKED_USER_SONGS"
export const GET_GET_USER_SONGS = "GET_GET_USER_SONGS"
export const GET_GET_PLAYLIST_SONGS = "GET_GET_PLAYLIST_SONGS"
export const GET_GET_SONG_BY_ID = "GET_GET_SONG_BY_ID"

// END SONG ACTIONS //

// PLAYLIST ACTIONS //

//POST

export const POST_POST_CREATE_PLAYLIST = "POST_POST_CREATE_PLAYLIST"
export const POST_POST_ADD_SONG_TO_PLAYLIST = "POST_POST_ADD_SONG_TO_PLAYLIST"
export const POST_POST_COMMENT_PLAYLIST = "POST_POST_COMMENT_PLAYLIST"
export const POST_POST_LIKE_PLAYLIST = "POST_POST_LIKE_PLAYLIST"

// GET

export const GET_GET_FOR_YOU_PLAYLIST = "GET_GET_FOR_YOU_PLAYLIST"
export const GET_GET_PLAYLIST_DETAIL = "GET_GET_PLAYLIST_DETAIL"
export const GET_GET_LIKED_USER_PLAYLIST = "GET_GET_LIKED_USER_PLAYLIST"

// END PLAYLIST ACTIONS //

export const SET_PLAYLIST_SONGS = "SET_PLAYLIST_SONGS"
export const SET_SONG = "SET_SONG"

//

export const POST_IMAGE = "POST_IMAGE";
export const GET_SEARCH = "GET_SEARCH"

